// Code generated by protoc-gen-go.
// source: chatmsg.proto
// DO NOT EDIT!

/*
Package protomsgs is a generated protocol buffer package.

It is generated from these files:
	chatmsg.proto

It has these top-level messages:
	ChatMsg
*/
package protomsgs

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

// 聊天消息
type ChatMsg struct {
	SenderName       *string `protobuf:"bytes,1,req" json:"SenderName,omitempty"`
	Msg              *string `protobuf:"bytes,2,req" json:"Msg,omitempty"`
	Timestamp        *int64  `protobuf:"varint,3,req" json:"Timestamp,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ChatMsg) Reset()         { *m = ChatMsg{} }
func (m *ChatMsg) String() string { return proto.CompactTextString(m) }
func (*ChatMsg) ProtoMessage()    {}

func (m *ChatMsg) GetSenderName() string {
	if m != nil && m.SenderName != nil {
		return *m.SenderName
	}
	return ""
}

func (m *ChatMsg) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

func (m *ChatMsg) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func init() {
}
